spring:
  datasource:
    url: jdbc:h2:file:~/test2;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: admin
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      
springdoc:
  
#  packagesToScan: com.mana.sample.api.*;
  swagger-ui:
    
    display-operation-id: true
    displayOperationId: true
    path: /swagger-ui
    display-request-duration: true
#    groups-order: DESC
#    operationsSorter: method
#    disable-swagger-default-url: true
#    use-root-path: true
  api-docs:
    
    path: /api-docs
  show-actuator: true
  
  
  
#springdoc.packagesToScan=com.neodem.orl.web